live :
  domain : www.bbc.com/flagpoles
  port : 3001
  source : <live S3 location>
test:
  domain : localhost:3001
  port : 3001
  source : s3://bbc-gnl-sandpit-dockerflagpole/flagpole_boolean.json
dev:
  domain : localhost:3000
  port : 3000
  source : test_flagpoles_file.json
