live :
  domain : www.bbc.com/flagpoles
  port : 80
  source : S3
staging :
  domain : www.bbc.com/flagpoles
  port : 80
  source : S3
test:
  domain : www.test.bbc.com/flagpoles
  port : 80
  source : S3
dev:
  domain : localhost:3000
  port : 3000
  source : test_flagpoles_file.json
