live :
  domain : www.bbc.com/flagpoles
  port : 3001
  source : flagpole_with_description.json
  s3_bucket : bbc-gnl-sandpit-dockerflagpole
  uses_s3 : true
test:
  domain : localhost:3001
  port : 3001
  source : flagpole_with_description.json
  s3_bucket : bbc-gnl-sandpit-dockerflagpole
  uses_s3 : true
dev:
  domain : localhost:3000
  port : 3000
  source : test_flagpoles_file.json
  uses_s3 : false
