live :
  domain : www.bbc.com/flagpoles
  port : 3002
  source : <live S3 location>
test:
  domain : www.test.bbc.com/flagpoles
  port : 3001
  source : <test S3 location>
dev:
  domain : localhost:3000
  port : 3000
  source : test_flagpoles_file.json
