common:
  api:
    url: https://cachestack-{platform}-pubstack.bbcverticals.com/api
live:
  domain: www.bbc.com
  clientApiUrl: /data
  staticBucket:
    url: 'https://cdn-static.bbcverticals.com'
  api:
    url: https://{habitatDomain}/api
    version: v1
    clientUrl: /data
    requestKey: JnesnhUFYZLTTgffWS8efzkSLKorzJZN
stage:
  _extends: live
test:
  domain: www.test.bbc.com
  api:
    url: https://cachestack-{platform}-pubstack.bbcverticals.com/api
dev:
  port: 3000
  domain: localhost:3000
