live :
  domain : www.bbc.com/flagpoles
  port : 3001
  usesS3: true
  s3Bucket: bbc-gnl-sandpit-dockerflagpole
  defaultSource: wwhp
  sources:
    wwhp : flagpole_with_description.json
    dotcom : flagpole_with_description.json
test:
  domain : localhost:3001
  port : 3001
  usesS3 : true
  s3Bucket : bbc-gnl-sandpit-dockerflagpole
  defaultSource : wwhp
  sources:
    wwhp : flagpole_with_description.json
    dotcom : flagpole_with_description.json
dev:
  domain : localhost:3000
  port : 3000
  usesS3 : false
  defaultSource : test
  sources :
    test : test_flagpoles_file.json
    wwhp : wwhp_flagpole_with_description.json
    dotcom : dotCom_flagpole_with_description.json

